# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: OracleXE # DNS name
  labels:
    app: OracleXE
    tier: database
spec:
  ports:
    - port: 1521
      targetPort: 1521
  selector: # oracle Pod Should contain same labels
    app: OracleXE
    tier: database
  clusterIP: None # We Use DNS, Thus ClusterIP is not relevant
---
# Define a 'Persistent Volume Claim'(PVC) for oracle Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: OracleXE
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Configure 'Deployment' of oracle server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: OracleXE
  labels:
    app: OracleXE
    tier: database
spec:
  selector: # oracle Pod Should contain same labels
    matchLabels:
      app: OracleXE
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: OracleXE
        tier: database
    spec:
      containers:
        - image: oracle/database:18.4.0-xe # image from docker-hub
          args:
            - "--shm-size=1g"
          name: OracleXE
          env:
            - name: ORACLE_PWD # Setting Root Password of oracle From a 'Secret'
              valueFrom:
                secretKeyRef:
                  name: db-credentials # Name of the 'Secret'
                  key: password # 'key' inside the Secret which contains required 'value'
          ports:
            - containerPort: 1521
              name: OracleXE
          volumeMounts: # Mounting voulume obtained from Persistent Volume Claim
            - name: oracle-persistent-storage
              mountPath: /var/lib/oracle
      volumes:
        - name: oracle-persistent-storage # Obtaining 'volume' from PVC
          persistentVolumeClaim:
            claimName: oracle-pv-claim
