# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: oracle-xe # DNS name
  labels:
    app: oracle-xe
    tier: database
spec:
  ports:
    - port: 1521
      name: listener
  selector: # oracle Pod Should contain same labels
    app: oracle-xe
    tier: database
  type: LoadBalancer
---
# Define a 'Persistent Volume Claim'(PVC) for oracle Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: oracle-xe
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# Configure 'Deployment' of oracle server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-xe
  labels:
    app: oracle-xe
    tier: database
spec:
  selector: # oracle Pod Should contain same labels
    matchLabels:
      app: oracle-xe
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: oracle-xe
        tier: database
    spec:
      containers:
        - name: oracle-xe
          image: adarshkumarsingh83/oracle:18.4.0-xe # image from docker-hub
          imagePullPolicy: IfNotPresent
          env:
            - name: ORACLE_PASSWORD # Setting Root Password of oracle From a 'Secret'
              valueFrom:
                secretKeyRef:
                  name: db-credentials # Name of the 'Secret'
                  key: password # 'key' inside the Secret which contains required 'value'
          ports:
            - containerPort: 1521
              name: listener
          volumeMounts: # Mounting volume obtained from Persistent Volume Claim
            - name: oracle-persistent-storage
              mountPath: /opt/oracle/oradata
      volumes:
        - name: oracle-persistent-storage # Obtaining 'volume' from PVC
          persistentVolumeClaim:
            claimName: oracle-pv-claim
