apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pv-claim
  labels:
    app: oracle-xe
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: oci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-xe
  labels:
    app: oracle-xe
spec:
  selector:
    matchLabels:
      app: oracle-xe
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle-xe
    spec:
      containers:
      - name: oracle-db
        image: adarshkumarsingh83/oracle-xe-21
        imagePullPolicy: IfNotPresent        
        env:
          - name: ORACLE_PWD # Setting Root Password of oracle From a 'Secret'
            valueFrom:
              secretKeyRef:
                name: db-credentials # Name of the 'Secret'
                key: password # 'key' inside the Secret which contains required 'value'
        ports:
        - containerPort: 1521
          name: oracle-db
        volumeMounts:
        - name: data
          mountPath: /opt/oracle/oradata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: oracle-pv-claim
---
apiVersion: v1
kind: Service
metadata:
 name: oracle-xe
spec:
 type: LoadBalancer
 ports:
   - name: client
     protocol: TCP
     port: 1521
     nodePort: 31521
 selector:
   app: oracle-xe
