logging:
  level:
    root: DEBUG

spring:
  application:
    name: springboot-kubernates-solr
  data:
    solr:
      repositories:
        enabled: true
      zk-host: localhost:2181
      host: localhost:8983
server:
  port: 8080


---

spring:
  application:
    name: springboot-kubernates-solr
  profiles:
    - docker
    - kubernates
  data:
    solr:
      repositories:
        enabled: true
      zk-host: ${ZOOKEEPER}
      host: ${SOLR_HOST}

server:
  port: 8080



