# Define 'Secret' to store 'root' user Credentials
apiVersion: v1
kind: Secret
metadata:
  name: espark-secret # Name of the Secret
  namespace: default
data:   #to create secret $ echo -n 'valuexxxx' | base64
  email: YWRhcnNoQGt1bWFyCg== # base64 encoded 'adarsh@kumar' email  => echo  'adarsh@kumar' | base64
  phone: OTk5OTk5OQo= # base64 encoded '9999999' phone => echo '9999999' | base64
  secretId: ZXNwYXJrCg== # base64 encoded 'espark' secretId -> echo 'espark' | base64