# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernates-secret
  namespace: default
spec:
  selector:  # backend application pod labels should match these
    app: springboot-kubernates-secret-label
    tier: backend
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer   # use NodePort, if you are not running Kubernetes on cloud
---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernates-secret
  labels:
    app: springboot-kubernates-secret-label
    tier: backend
spec:
  replicas: 1    # Number of replicas of back-end application to be deployed
  selector:
    matchLabels: # backend application pod labels should match these
      app: springboot-kubernates-secret-label
      tier: backend
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' labels
        app: springboot-kubernates-secret-label
        tier: backend
    spec:
      containers:
        - name: springboot-kubernates-secret
          image: adarshkumarsingh83/springboot-kubernates-secret  # docker image of backend application
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:   # Setting environmental Variables
            - name: SPRING_PROFILES_ACTIVE
              value: kubernates
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: espark-secret # Secret Name
                  key: email # Secret key name
            - name: PHONE
              valueFrom:
                secretKeyRef:
                  name: espark-secret
                  key: phone
            - name: SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: espark-secret
                  key: secretId