version: '3.7'
services:
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      - solr

  solr1:
    image: solr:8.3
    container_name: solr1
    ports:
     - "8981:8983"
    environment:
      - ZK_HOST=zookeeper:2181
    networks:
      - solr
    depends_on:
      - zookeeper

  solr2:
    image: solr:8.3
    container_name: solr2
    ports:
     - "8982:8983"
    environment:
      - ZK_HOST=zookeeper:2181
    networks:
      - solr
    depends_on:
      - zookeeper

  solr3:
    image: solr:8.3
    container_name: solr3
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zookeeper:2181
    networks:
      - solr
    depends_on:
      - zookeeper

networks:
  solr: