spring:
  application:
    name: springboot-web-rest
  output:
    ansi:
      enabled: DETECT

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  file: /var/log/containers/${spring.application.name}-eflk.log
  level:
    org.springframework.web: DEBUG
    com.espark.adarsh: DEBUG

server:
  port: 8080
