FROM openjdk:8
MAINTAINER adarsh.kumar@gmail.com
COPY target/springboot-kubernetes-elasticsearch-kibana.jar springboot-kubernetes-elasticsearch-kibana.jar
ENTRYPOINT ["java","-jar","springboot-kubernetes-elasticsearch-kibana.jar"]