FROM openjdk:8
MAINTAINER adarshkumarsingh83@gmail.com
ADD target/springboot-kubernates-ngnix.jar springboot-kubernates-ngnix.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","springboot-kubernates-ngnix.jar"]