server:
  port: 8080

spring:
  output:
    ansi:
      enabled: DETECT
  application:
    name: springboot-service
  config:
    activate:
      on-profile:
        - default
logging:
  file.name: logs/app.log
  pattern:
    console: "%d [%t] %-5level %logger{36} - %msg%n"
    file: "%d [%t] %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    com.espark.adarsh: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
---

spring:
  output:
    ansi:
      enabled: DETECT
  application:
    name: springboot-service
  config:
    activate:
      on-profile:
        - docker
        - kubernates
logging:
  file:
    name: /var/logs/application.log
    max-size: 1MB
    max-history: 10
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.zip
    level: '${spring.application.name} - [%X{traceId}/%X{spanId}] %X{sessionId}  %-5p [%t] %C{2} - %m%n'
  level:
    root: DEBUG
    com.espark.adarsh: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
