server:
  port: 8080

spring:
  output:
    ansi:
      enabled: DETECT
  application:
    name: springboot-service
  config:
    activate:
      on-profile:
        - default
logging:
  file.name: /Users/us-guest/logs/app.log
  pattern:
    console: "%d [%t] %-5level %logger{36} - %msg%n"
    file: "%d [%t] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.espark.adarsh: INFO
    org.springframework: INFO
    org.springframework.web: INFO

---

spring:
  output:
    ansi:
      enabled: DETECT
  application:
    name: springboot-service
  config:
    activate:
      on-profile:
        - docker
        - kubernates
logging:
  file:
    name: /var/logs/app.log
    max-size: 1MB
    max-history: 10
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.zip
  level:
    root: INFO
    com.espark.adarsh: INFO
    org.springframework: INFO
    org.springframework.web: INFO
