server:
  port: 8080

logging:
  level:
    root: DEBUG

spring:
  application:
    name: springboot-kubernetes-elasticsearch-kibana
  profiles:
    - defualt
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 'localhost:9300'
      cluster-name: 'elasticsearch'


elasticsearch:
  index:
    name: epsark-index
  user:
    type: user

application:
  elastic:
    url: localhost:9200

---

server:
  port: 8080

logging:
  level:
    root: DEBUG

spring:
  application:
    name: springboot-kubernetes-elasticsearch-kibana
  profiles:
    - kubernetes
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: ${ELASTIC_NODES}
      cluster-name: ${ELASTIC_NAME}


elasticsearch:
  index:
    name: ${ELASTIC_INDEX}
  user:
    type: user

application:
  elastic:
    url: ${ELASTIC_URL}