version: '3'
services:

  springboot-kubernates-ngnix1:
    container_name: springboot-kubernates-ngnix1
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - '8081:8081'
    networks:
      - spring-ms

  springboot-kubernates-ngnix2:
    container_name: springboot-kubernates-ngnix2
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - '8082:8082'
    networks:
      - spring-ms

  springboot-kubernates-ngnix3:
    container_name: springboot-kubernates-ngnix3
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - '8083:8083'
    networks:
      - spring-ms

  springboot-kubernates-ngnix4:
    container_name: springboot-kubernates-ngnix4
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - '8084:8084'
    networks:
      - spring-ms

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./config/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - springboot-kubernates-ngnix1
      - springboot-kubernates-ngnix2
      - springboot-kubernates-ngnix3
      - springboot-kubernates-ngnix4
    links:
      - springboot-kubernates-ngnix1
      - springboot-kubernates-ngnix2
      - springboot-kubernates-ngnix3
      - springboot-kubernates-ngnix4
    networks:
      - spring-ms

networks:
  spring-ms: