apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: espark-config-server
  name: espark-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: espark-config-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: espark-config-server
    spec:
      containers:
      - image: adarshkumarsingh83/espark-config-server
        name: espark-config-server
        ports:
          - containerPort: 8888
        env:
          - name: REGISTRY_HOST
            value: espark-eureka-server
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: espark-config-server
  name: espark-config-server
spec:
  ports:
  - name: 8888-8888
    port: 8888
    protocol: TCP
    targetPort: 8888
    nodePort: 30002
  selector:
    app: espark-config-server
  type: LoadBalancer
status:
  loadBalancer: {}
