apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: espark-employee-service
  name: espark-employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: espark-employee-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: espark-employee-service
    spec:
      containers:
      - image: adarshkumarsingh83/espark-employee-service
        name: espark-employee-service
        env:
          - name: REGISTRY_HOST
            value: espark-eureka-server
        resources: {}
status: {}
