apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
spec:
  serviceName: solr
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
        - name: solr
          image: bitnami/solr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8983
          env:
            - name: SOLR_CORE
              value: employee
          volumeMounts:
            - name: data
              mountPath: /var/lib/solr
      volumes:
        - name: data
          hostPath:
            path: /data/solr
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: solr
  labels:
    service: solr
spec:
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983
  selector:
    app: solr
  type: LoadBalancer