FROM openjdk:8
MAINTAINER adarshkumarsingh83@gmail.com
COPY target/springboot-kubernates-hazelcast.jar springboot-kubernates-hazelcast.jar
ENTRYPOINT ["java","-jar","springboot-kubernates-hazelcast.jar"]