FROM openjdk:8
MAINTAINER adarsh.kumar@gmail.com
COPY target/springboot-kubernetes-elk-sidecar-container.jar springboot-kubernetes-elk-sidecar-container.jar
ENTRYPOINT ["java","-jar","springboot-kubernetes-elk-sidecar-container.jar"]