apiVersion: v1
kind: ConfigMap
metadata:
  name: ngix-logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      
      file {
              path => "/var/log/nginx/*.log"
              codec => multiline {
              pattern => "^%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{TIME}.*"
              negate => "true"
              start_position => beginning
           }
      }

      output {
          stdout {
              codec => rubydebug
          }
          elasticsearch{
              hosts=>["http://elasticsearch:9200"]
              index=>"esaprk-%{+YYYY.MM.dd}"
          }
      }