apiVersion: v1
kind: ConfigMap
metadata:
  name: service-logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      file {
        type => "java"
        path => "/var/logs/app.log"
        #codec => "plain"
        start_position => "beginning"
        codec => multiline {
          pattern => "^%{YEAR}-%{MONTHNUM}-%{MONTHDAY}.*"
          negate => "true"
          what => "previous"
        }
      }
      file {
        type => "ngix"
        path => "/var/log/nginx/*.log"
      }
    }

    output {
        stdout {
            codec => rubydebug
        }
        elasticsearch { 
            hosts=>["http://elasticsearch:9200"]
            index => "espark-%{+YYYY.MM.dd}"
        }
    }