apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernates-hazelcast
  labels:
    app: springboot-kubernates-hazelcast
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-kubernates-hazelcast
  template:
    metadata:
      labels:
        app: springboot-kubernates-hazelcast
    spec:
      containers:
        - name: springboot-kubernates-hazelcast
          image: adarshkumarsingh83/springboot-kubernates-hazelcast
          ports:
            - name: http
              containerPort: 8080
            - name: multicast
              containerPort: 5701
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernates-hazelcast
  labels:
    app: springboot-kubernates-hazelcast
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: springboot-kubernates-hazelcast
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service
spec:
  selector:
    app: springboot-kubernates-hazelcast
  ports:
    - name: hazelcast
      port: 5701
  type: LoadBalancer