apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
          env:
            - name: discovery.type
              value: single-node
            - name: cluster.name
              value: espark-cluster
          ports:
            - containerPort: 9200
              name: client
          volumeMounts:
            - name: data
              mountPath: /var/lib/elasticsearch
      volumes:
        - name: data
          hostPath:
            path: /data/elasticsearch
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  ports:
    - port: 9200
      name: client
  selector:
    app: elasticsearch
  type: LoadBalancer
