apiVersion: apps/v1
kind: Deployment
metadata:
  name: espark-config-server
  labels:
    app: espark-config-server
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: espark-config-server
      tier: backend
  template:
    metadata:
      labels:
        app: espark-config-server
        tier: backend
    spec:
      containers:
        - image: adarshkumarsingh83/espark-config-server
          name: espark-config-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:   # Setting environmental Variables
            - name: SPRING_PROFILES_ACTIVE
              value: kubernates
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: cluster-config # name of configMap
                  key: eureka
---

apiVersion: v1
kind: Service
metadata:
  name: espark-config-server
  labels:
    app: espark-config-server
    tier: backend
spec:
  selector:
    app: espark-config-server
    tier: backend
  ports:
    - name: 8888-8888
      port: 8888
      protocol: TCP
      targetPort: 8888
  type: LoadBalancer

