apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-service
spec:
  selector:
    matchLabels:
      app: springboot-service
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-service
        tier: backend
        track: stable
    spec:
      containers:
        - name: springboot-service
          image: "adarshkumarsingh83/springboot-service"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env: # Setting environmental Variables
            - name: SPRING_PROFILES_ACTIVE
              value: kubernates
            - name: LOGGING_FILE_PATH
              value: /var/logs/
            - name: LOGGING_FILE_NAME
              value: /var/logs/app.logs
          volumeMounts:
            - mountPath: /var/logs
              name: logs
      volumes:            
        - name: logs
          emptyDir: {}
              
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-service
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer