apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-service2
spec:
  selector:
    matchLabels:
      app: springboot-service2
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-service2
        tier: backend
        track: stable
    spec:
      containers:
        - name: springboot-service2
          image: "adarshkumarsingh83/springboot-service"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env: # Setting environmental Variables
            - name: SPRING_PROFILES_ACTIVE
              value: kubernates
            - name: LOGGING_FILE_PATH
              value: /var/logs/
            - name: LOGGING_FILE_NAME
              value: /var/logs/app.logs
          volumeMounts:
            - mountPath: /var/logs
              name: logs
        - name: logstash
          image: docker.elastic.co/logstash/logstash:6.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config
            - name: logstash-pipeline-volume
              mountPath: /usr/share/logstash/pipeline
            - mountPath: /var/logs
              name: logs
      volumes:
        - name: config-volume
          configMap:
            name: service-logstash-configmap
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: logstash-pipeline-volume
          configMap:
            name: service-logstash-configmap
            items:
              - key: logstash.conf
                path: logstash.conf                
        - name: logs
          emptyDir: {}
              
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-service2
spec:
  selector:
    app: springboot-service2
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort