# Define 'Secret' to store 'root' user Credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials # Name of the Secret
  namespace: default
data:   #to create secret $ echo -n 'valuexxxx' | base64
  username: cm9vdA== # base64 encoded 'root' username
  password: cm9vdA== # base64 encoded 'root' password  