apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper
  type: LoadBalancer

---

apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: zookeeper
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: zookeeper
      spec:
        initContainers:
          - name: volume-permissions
            image: busybox
            command: ['sh', '-c', 'chmod -R g+rwX /bitnami']
            volumeMounts:
              - mountPath: /bitnami
                name: zookeeper-data
        containers:
          - image: bitnami/zookeeper:latest
            name: zookeeper
            env:
              - name: ALLOW_ANONYMOUS_LOGIN
                value: "yes"
            ports:
              - containerPort: 2181
            resources: {}
            volumeMounts:
              - mountPath: /bitnami/zookeeper
                name: zookeeper-data
        restartPolicy: Always
        volumes:
          - name: zookeeper-data
            persistentVolumeClaim:
              claimName: zookeeper-data
  status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper-data
  name: zookeeper-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
