apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr1
spec:
  serviceName: solr1
  replicas: 1
  selector:
    matchLabels:
      app: solr1
  template:
    metadata:
      labels:
        app: solr1
    spec:
      containers:
        - name: solr1
          image: solr:8
          imagePullPolicy: Always
          ports:
            - containerPort: 8983
          env:
            - name: ZK_HOST
              valueFrom:
                configMapKeyRef:
                  name: application-conf
                  key: zk_url
          volumeMounts:
            - name: data
              mountPath: /var/lib/solr
      volumes:
        - name: data
          hostPath:
            path: /data/solr
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: solr1
  labels:
    service: solr1
spec:
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983
  selector:
    app: solr1
  type: LoadBalancer