FROM openjdk:8
MAINTAINER adarshkumarsingh83@gmail.com
COPY target/springboot-hazelcast-kubernates.jar springboot-hazelcast-kubernates.jar
ENV JAVA_OPTS=""
ENTRYPOINT ["java","-jar","springboot-hazelcast-kubernates.jar"]