kind: Service
apiVersion: v1
metadata:
  name: espark-address-service
spec:
  selector:
    app: espark-address-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30084
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: espark-address-service
spec:
  selector:
    matchLabels:
      app: espark-address-service
  replicas: 1
  template:
    metadata:
      labels:
        app: espark-address-service
    spec:
      containers:
        - name: espark-address-service
          image: "adarshkumarsingh83/espark-address-service"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:   # Setting environmental Variables
            - name: SPRING_PROFILES_ACTIVE
              value: kubernates