apiVersion: v1
kind: ConfigMap
metadata:
  name: application-conf           # name of ConfigMap, referenced in other files
  namespace: default
data:
  host: "mysql"            # host address of mysql server, we are using DNS of Service
  name: "espark-mysql"    # name of the database for application
  port: "3306"
  zk_url: "zookeeper:2181"
  kafka_url: "kafka:9092"
  kafka_topic: "espark-topic"
  kafka_ad_port: "9092"
