apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
              name: client
          env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            valueFrom:
              configMapKeyRef:
                name: application-conf
                key: zk_url
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: 192.168.1.240
          - name: KAFKA_ADVERTISED_PORT
            valueFrom:
              configMapKeyRef:
                name: application-conf
                key: kafka_ad_port
          - name: KAFKA_BROKER_ID
            value: "0"
          - name: KAFKA_CREATE_TOPICS
            valueFrom:
              configMapKeyRef:
                name: application-conf
                key: kafka_topic
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
      volumes:
        - name: data
          hostPath:
            path: /data/kafka
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    service: kafka
spec:
  ports:
    - port: 9092
      name: client
  selector:
    app: kafka
  type: LoadBalancer