apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_PORT
              value: 9092
            - name: KAFKA_CREATE_TOPICS
              value: espark-topic
          ports:
            - containerPort: 9092
              name: client
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
      volumes:
        - name: data
          hostPath:
            path: /data/kafka
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    service: kafka
spec:
  ports:
    - port: 9092
      name: client
  selector:
    app: kafka
  type: LoadBalancer