# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: springboot-kafka-producer
  namespace: default
spec:
  selector:  # backend application pod labels should match these
    app: springboot-kafka-producer-label
    tier: backend
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
  type: LoadBalancer   # use NodePort, if you are not running Kubernetes on cloud
---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kafka-producer
  labels:
    app: springboot-kafka-producer-label
    tier: backend
spec:
  replicas: 1    # Number of replicas of back-end application to be deployed
  selector:
    matchLabels: # backend application pod labels should match these
      app: springboot-kafka-producer-label
      tier: backend
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' labels
        app: springboot-kafka-producer-label
        tier: backend
    spec:
      containers:
        - name: springboot-kafka-producer
          image: adarshkumarsingh83/springboot-kafka-producer  # docker image of backend application
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          env:   # Setting environmental Variables
            - name: SPRING_PROFILES_ACTIVE
              value: kubernates
            - name: KAFKA_URL # Setting KAFKA URL FROM CONFIG MAP
              valueFrom:
                configMapKeyRef:
                  name: application-conf
                  key: kafka_url