
# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
spec:
  selector:  # backend application pod labels should match these
    app: zookeeper-label
    tier: backend
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: LoadBalancer   # use NodePort, if you are not running Kubernetes on cloud
---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper-label
    tier: backend
spec:
  replicas: 1    # Number of replicas of back-end application to be deployed
  selector:
    matchLabels: # backend application pod labels should match these
      app: zookeeper-label
      tier: backend
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' labels
        app: zookeeper-label
        tier: backend
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:latest  # docker image of backend application
          imagePullPolicy: Always
          ports:
            - containerPort: 2181