FROM openjdk:8
MAINTAINER adarshkumarsingh83@gmail.com
ADD target/springboot-kubernates-elasticsearch.jar springboot-kubernates-elasticsearch.jar
EXPOSE 9090
ENTRYPOINT ["java","-jar","springboot-kubernates-elasticsearch.jar"]