version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./db:/usr/share/elasticsearch/data
    networks:
      - spring-ms

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - spring-ms

  springboot-kubernates-elasticsearch:
    container_name: springboot-kubernates-elasticsearch
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - '9090:9090'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DOCKER-ELASTIC-URL=elasticsearch:9200
    networks:
      - spring-ms

networks:
  spring-ms: