apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: hazelcast
spec: 
  replicas: 2
  serviceName: hazelcast
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata: 
      labels: 
        app: hazelcast
    spec: 
      containers: 
        - image: hazelcast/hazelcast
          name: hazelcast
          imagePullPolicy: Always
          ports:
            - name: hazelcast
              protocol: TCP
              containerPort: 5701
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: management-center
spec:
  replicas: 1
  serviceName: management-center
  selector:
    matchLabels:
      app: management-center  
  template:
    metadata:
      labels:
        app: management-center
    spec:
      containers:
      - name: management-center
        image: hazelcast/management-center
---
kind: Service
apiVersion: v1
metadata:
  name: management-center
spec:
  type: LoadBalancer
  selector:
    app: management-center
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
