# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: springboot-kafka-consumer
  namespace: default
spec:
  selector:  # backend application pod labels should match these
    app: springboot-kafka-consumer-label
    tier: backend
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191
  type: LoadBalancer   # use NodePort, if you are not running Kubernetes on cloud
---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kafka-consumer
  labels:
    app: springboot-kafka-consumer-label
    tier: backend
spec:
  replicas: 1    # Number of replicas of back-end application to be deployed
  selector:
    matchLabels: # backend application pod labels should match these
      app: springboot-kafka-consumer-label
      tier: backend
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' labels
        app: springboot-kafka-consumer-label
        tier: backend
    spec:
      containers:
        - name: springboot-kafka-consumer
          image: adarshkumarsingh83/springboot-kafka-consumer  # docker image of backend application
          imagePullPolicy: Always
          ports:
            - containerPort: 9191
          env:   # Setting environmental Variables
            - name: SPRING_PROFILES_ACTIVE
              value: kubernates
            - name: DATABASE_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: application-conf # name of configMap
                  key: host
            - name: DATABASE_PORT   # Setting Database port  from configMap
              valueFrom:
                configMapKeyRef:
                  name: application-conf # name of configMap
                  key: port
            - name: DATABASE_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: application-conf
                  key: name
            - name: DATABASE_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials # Secret Name
                  key: username
            - name: DATABASE_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            - name: KAFKA_URL # Setting KAFKA URL FROM CONFIG MAP
              valueFrom:
                configMapKeyRef:
                  name: application-conf
                  key: kafka_url