# Define 'Secret' to store 'root' user Credentials
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials # Name of the Secret
  namespace: default
data:   #to create secret $ echo -n 'valuexxxx' | base64
  rootPassword: bWFnaWM= # base64 encoded 'root' password
  username: dXNlcg==  # base64 encoded 'Secret' username
  password: ZGV2ZWxvcA== # base64 encoded 'Secret' password
