apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf           # name of ConfigMap, referenced in other files
  namespace: default
data:
  host: "mysql"            # host address of mysql server, we are using DNS of Service
  name: "espark-mysql"    # name of the database for application
  port: "3306"
