version: '3.7'
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.0.3
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/secret
      NEO4J_dbms_logs_debug_level: DEBUG