version: "3"
services:
  hazelcast:
    image: 'hazelcast/hazelcast:3.12.7'
    container_name: hazelcast
    ports:
      - '5701:5701'
    restart: always

    environment:
      - "-Dhazelcast.local.publicAddress=192.168.99.100:5701"
      - "-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.xml"
    networks:
      - spring-ms

  management-center:
    image: 'hazelcast/management-center:latest'
    container_name: management-center
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - hazelcast
    links:
      - hazelcast
    networks:
      - spring-ms

  springboot-kubernates-hazelcast-external:
    container_name: springboot-kubernates-hazelcast-external
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - '9090:9090'
    depends_on:
      - hazelcast
    links:
      - hazelcast
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring-ms

networks:
  spring-ms: