version: "3"
services:
  hazelcast:
    image: hazelcast/hazelcast:4.0.1
    container_name: hazelcast
    ports:
      - 5701
    networks:
      - spring-ms

  management-center:
    image: hazelcast/management-center:4.0.3
    container_name: management-center
    environment:
      - MC_INIT_CMD=./mc-conf.sh cluster add -H=/data -ma hazelcast:5701 -cn dev
    ports:
      - 8080:8080
    depends_on:
      - hazelcast
    links:
      - hazelcast
    restart: always
    networks:
      - spring-ms

  springboot-kubernates-hazelcast-external:
    container_name: springboot-kubernates-hazelcast-external
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - '9090:9090'
    depends_on:
      - hazelcast
    links:
      - hazelcast
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring-ms

networks:
  spring-ms: