FROM openjdk:8
MAINTAINER adarshkumarsingh83@gmail.com
ADD target/springboot-kubernates-hazelcast-external.jar springboot-kubernates-hazelcast-external.jar
EXPOSE 9090
ENTRYPOINT ["java","-jar","springboot-kubernates-hazelcast-external.jar"]