FROM openjdk:8
MAINTAINER adarshkumarsingh83@gmail.com
ADD target/springboot-kubernates-secret.jar springboot-kubernates-secret.jar
EXPOSE 9090
ENTRYPOINT ["java","-jar","springboot-kubernates-secret.jar"]