FROM openjdk:8
MAINTAINER adarshkumarsingh83@gmail.com
ADD target/springboot-kubernates-solr-cloud.jar springboot-kubernates-solr-cloud.jar
EXPOSE 9090
ENTRYPOINT ["java","-jar","springboot-kubernates-solr-cloud.jar"]