server:
  port: 9090


spring:
  application:
    name: springboot-elasicsearch
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9200

application:
  elastic:
    url: localhost:9200

---

spring:
  application:
    name: springboot-elasicsearch
  data:
    elasticsearch:
      cluster-name: ${DOCKER-CLUSTER-NAME}
      cluster-nodes: ${DOCKER-ELASTIC-URL}
  profiles:
    - docker
    - kubernates

application:
  elastic:
    url: ${DOCKER-ELASTIC-URL}