FROM openjdk:8
MAINTAINER adarsh.kumar@gmail.com
COPY target/springboot-kubernetes-redis-cache.jar springboot-kubernetes-redis-cache.jar
ENTRYPOINT ["java","-jar","springboot-kubernetes-redis-cache.jar"]