version: '3.1'
services:

  oracledb:
    image: oracle/database:18.4.0-xe
    container_name: OracleXE
    environment:
      - shm-size=1g
      - ORACLE_PWD=12345
    ports:
      - "1521:1521"
      - "8081:8081"
    volumes:
      - ./db:/u01/app/oracle/oradata 
    networks:
     - espark-net

  oracledb-liquibse:
    container_name: oracledb-liquibse
    build: ./oracle-liquibase-docker
    restart: always
    environment:
     - DB_URL=jdbc:oracle:thin:@OracleXE:1521:XE
     - DB_USERNAME=SYSTEM
     - DB_PASSWORD=12345
    links:
      - oracledb
    depends_on:
      - oracledb
    networks:
     - espark-net

  springboot-services:
    container_name: springboot-services
    build: ./springboot-oracledb-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_HOST=OracleXE
      - DATABASE_USER=SYSTEM
      - DATABASE_PASSWORD=12345
    links:
      - oracledb
    depends_on:
      - oracledb
      - oracledb-liquibse
    networks:
     - espark-net

networks:
  espark-net: