server:
  port: 9090

spring:
  application:
    name: springboot-jpa-postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/esparkdb
    username: root
    password: root1234
    driver-class-name: org.postgresql.Driver
    #initialization-mode: always
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      #ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---

spring:
  application:
    name: springboot-jpa-postgres
  profiles: docker
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    platform: postgres
    driver-class-name:  org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      initialization-fail-timeout: 100
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---

spring:
  application:
    name: springboot-jpa-postgres
  profiles: kubernates
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    platform: postgres
    driver-class-name:  org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      initialization-fail-timeout: 100
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl