apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernates-ngnix3
spec:
  selector:
    matchLabels:
      app: springboot-kubernates-ngnix3
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-kubernates-ngnix3
        tier: backend
        track: stable
    spec:
      containers:
        - name: springboot-kubernates-ngnix3
          image: "adarshkumarsingh83/springboot-kubernates-ngnix"
          ports:
            - name: http
              containerPort: 8080
              
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernates-ngnix3
spec:
  selector:
    app: springboot-kubernates-ngnix3
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort