
spring:
  application:
    name: springboot-kubernetes-neo4j
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: secret

server:
  port: 8080

---

spring:
  application:
    name: springboot-kubernetes-neo4j
  profiles:
    - docker
    - kubernates
  data:
    neo4j:
      uri: ${NEO4J_URL}
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_USERPWD}

server:
  port: 8080