apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zookeeper1
            - name: ZOOKEEPER_SERVER_2
              value: zookeeper2

---

kind: Service
apiVersion: v1
metadata:
  name: zoo1
spec:
  type: LoadBalancer
  ports:
    - name: port-2181
      port: 2181
      protocol: TCP
    - name: port-2888
      port: 2888
      protocol: TCP
    - name: port-3888
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper1

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 172.31.25.198
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper1:2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: LoadBalancer
  externalIPs:
    - 172.31.25.198
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka