apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging  
  labels:
    app: fluent-bit
data:
  elasticsearch_host: "elasticsearch.logging"
  elasticsearch_port: "9200"
  elasticsearch_url: "http://elasticsearch.logging:9200"
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Merge_Log_Trim On
        Labels On
        Annotations Off
        K8S-Logging.Parser Off
        K8S-Logging.Exclude Off

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [OUTPUT]
        Name es
        Match kube.*
        Host ${ELASTICSEARCH_HOST}
        Port  ${ELASTICSEARCH_PORT}
        Index fluent_bit_index

