apiVersion: v1
kind: Service
metadata:
  name: solr
  namespace: default
spec:
  selector:
    app: solr
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  labels:
    app: solr
spec:
  replicas: 1    # Number of replicas of back-end application to be deployed
  selector:
    matchLabels: # backend application pod labels should match these
      app: solr
  template:
    metadata:
      labels:     # Must match 'Service' and 'Deployment' labels
        app: solr
    spec:
      restartPolicy: Always
      containers:
        - name: solr
          image: solr:8.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8983
        - name: solr
            command:
              - "/bin/bash"
              - "-c"
              - "/opt/docker-solr/scripts/startService.sh"
              - solr-precreate
              - employee