apiVersion: apps/v1
kind: Deployment
metadata:
  name: espark-eureka-server
  labels:
    app: espark-eureka-server
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: espark-eureka-server
      tier: backend
  template:
    metadata:
      labels:
        app: espark-eureka-server
        tier: backend
    spec:
      containers:
      - image: adarshkumarsingh83/espark-eureka-server
        name: espark-eureka-server
        imagePullPolicy: Always
        ports:
          - containerPort: 8761
        env:   # Setting environmental Variables
          - name: SPRING_PROFILES_ACTIVE
            value: kubernates

---

apiVersion: v1
kind: Service
metadata:
  name: espark-eureka-server
  labels:
    app: espark-eureka-server
    tier: backend
spec:
  selector:
    app: espark-eureka-server
    tier: backend
  ports:
  - name: 8761-8761
    port: 8761
    protocol: TCP
    targetPort: 8761
  type: LoadBalancer

