spring:
  application:
    name: springboot-kubernetes-elk
  profiles:
    - default
  logstash:
    enabled: true
    url: localhost:5000
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      enabled: true
    health:
      enabled: true
    env:
      enabled: true
  security:
    enabled: false

info:
  app:
    name: springboot-kubernetes-elk
    description: springboot-kubernetes-elk
    version: 1.0.0

server:
  port: 8080

logging:
  level:
    root: DEBUG
    com.espark.adarsh: DEBUG
    org.springframework.web: DEBUG
    group:
      com.espark.adarsh: DEBUG
      org.springframework.web: DEBUG
  file:
    name: ${user.home}/var/logs/application.log
    max-size: 1MB
    max-history: 10
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.zip
    level: '${spring.application.name} - [%X{traceId}/%X{spanId}] %X{sessionId}  %-5p [%t] %C{2} - %m%n'

---

spring:
  application:
    name: springboot-kubernetes-elk
  profiles:
    - kubernetes
  logstash:
    enabled: true
    url: ${LOGSTASH_URL:'logstash:5000'}
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      enabled: true
    health:
      enabled: true
    env:
      enabled: true
  security:
    enabled: false

info:
  app:
    name: springboot-kubernetes-elk
    description: springboot-kubernetes-elk
    version: 1.0.0

server:
  port: 8080

logging:
  level:
    root: DEBUG
    com.espark.adarsh: DEBUG
    org.springframework.web: DEBUG
    group:
      com.espark.adarsh: DEBUG
      org.springframework.web: DEBUG
  file:
    name: /var/logs/application.log
    max-size: 1MB
    max-history: 10
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.zip
    level: '${spring.application.name} - [%X{traceId}/%X{spanId}] %X{sessionId}  %-5p [%t] %C{2} - %m%n'