spring:
  application:
    name: espark-eureka-server
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  datacenter: India
  environment: production

---

spring:
  application:
    name: espark-eureka-server
  profiles:
    - docker
    - kubernates
eureka:
  datacenter: India
  environment: production
  client:
    register-with-eureka: false
    fetch-registry: false
