apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: hazelcast
spec: 
  replicas: 2
  serviceName: hazelcast
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata: 
      labels: 
        app: hazelcast
    spec: 
      containers: 
        - image: hazelcast/hazelcast:4.0.1
          name: hazelcast
          imagePullPolicy: Always
          ports:
            - name: hazelcast
              protocol: TCP
              containerPort: 5701
---
kind: Service
apiVersion: v1
metadata:
  name: hazelcast
spec:
  type: LoadBalancer
  selector:
    app: hazelcast
  ports:
    - protocol: TCP
      port: 5701
      targetPort: 5701
