apiVersion: v1
kind: Service
metadata:
  name: management-center
spec:
  type: LoadBalancer
  selector:
    app: management-center
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-center
  labels:
    app: management-center
spec:
  replicas: 1    # Number of replicas of back-end application to be deployed
  selector:
    matchLabels: # backend application pod labels should match these
      app: management-center
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' labels
        app: management-center
    spec:
      containers:
        - name: management-center
          image: hazelcast/management-center:4.0.3
          imagePullPolicy: Always
          ports:
            - name: mc
              protocol: TCP
              containerPort: 8080
          env:   # Setting environmental Variables
            - name: MC_INIT_CMD
              value: ./mc-conf.sh cluster add -H=/data -ma hazelcast:5701 -cn dev