logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG

spring:
  application:
    name: springboot-kubernates-configmap

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health
